In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('50_Startups.csv')

In [3]:
df.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [70]:
x = df.iloc[:, :-1].values
y = df.iloc[:,4].values

In [72]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [73]:
labelencoder_x = LabelEncoder()
onehotencoder = OneHotEncoder(categorical_features = [3])

In [75]:
x[:,3] = labelencoder_x.fit_transform(x[:,3])

In [76]:
x = onehotencoder.fit_transform(x).toarray()

/home/danyshman/miniconda3/envs/datascience/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/danyshman/miniconda3/envs/datascience/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [77]:
pd.DataFrame(x)

      0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

In [78]:
from sklearn.model_selection import train_test_split

In [110]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2,random_state=0)

In [111]:
from sklearn.linear_model import LinearRegression

In [112]:
regressor = LinearRegression()

In [113]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [114]:
y_pred = regressor.predict(x_test)

In [85]:
pd.DataFrame(y_pred)

                0
0   104282.764722
1   132536.884992
2   133910.850078
3    72584.774894
4   179920.927619
5   114549.310792
6    66444.432613
7    98404.968401
8   114499.828086
9   169367.506399
10   96522.625400
11   88040.671829
12  110949.994055
13   90419.189785
14  128020.462501

In [86]:
pd.DataFrame(y_test)

            0
0   103282.38
1   144259.40
2   146121.95
3    77798.83
4   191050.39
5   105008.31
6    81229.06
7    97483.56
8   110352.25
9   166187.94
10   96778.92
11   96479.51
12  105733.54
13   96712.80
14  124266.90

In [87]:
import statsmodels.formula.api as sm

In [88]:
x = np.append(arr=np.ones((50,1)).astype(int),values=x,axis=1)

In [89]:
x_opt = x[:,[0,1,2,3,4,5,6]]

In [90]:
regressor_ols = sm.OLS(endog=y, exog = x_opt).fit()

In [91]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Mon, 20 May 2019   Prob (F-statistic):           1.34e-27
Time:                        19:06:55   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.763e+04   5073.636      7.417      0.000    2.74e+04    4.79e+04
x1          1.249e+04   2449.797      5.099      0.000    7554.868    1.74e+04
x2          1.269e+04   2726.700      4.654      0.000    7195.596    1.82e+04
x3          1.245e+04   2486.364      5.007      0.000    7439.285    1.75e+04
x4             0.8060      0.046     17.369      0.000       0.712       0.900
x5            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x6             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.81e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.18e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [92]:
x_opt = x[:,[0,1,2,3,4,5]]
regressor_ols = sm.OLS(endog=y, exog = x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     205.0
Date:                Mon, 20 May 2019   Prob (F-statistic):           2.90e-28
Time:                        19:07:05   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1064.
Df Residuals:                      45   BIC:                             1073.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.122e+04   4607.941      8.945      0.000    3.19e+04    5.05e+04
x1          1.339e+04   2421.500      5.529      0.000    8511.111    1.83e+04
x2          1.448e+04   2518.987      5.748      0.000    9405.870    1.96e+04
x3          1.335e+04   2459.306      5.428      0.000    8395.623    1.83e+04
x4             0.8609      0.031     27.665      0.000       0.798       0.924
x5            -0.0527      0.050     -1.045      0.301      -0.154       0.049
==============================================================================
Omnibus:                       14.275   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.260
Skew:                          -0.953   Prob(JB):                     6.57e-05
Kurtosis:                       5.369   Cond. No.                     9.18e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.28e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [93]:
x_opt = x[:,[0,1,2,3,4]]
regressor_ols = sm.OLS(endog=y, exog = x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.4
Date:                Mon, 20 May 2019   Prob (F-statistic):           2.76e-29
Time:                        19:07:10   Log-Likelihood:                -527.35
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.686e+04   1959.786     18.806      0.000    3.29e+04    4.08e+04
x1          1.189e+04   1956.677      6.079      0.000    7955.697    1.58e+04
x2          1.306e+04   2122.665      6.152      0.000    8785.448    1.73e+04
x3           1.19e+04   2036.022      5.847      0.000    7805.580     1.6e+04
x4             0.8530      0.030     28.226      0.000       0.792       0.914
==============================================================================
Omnibus:                       13.418   Durbin-Watson:                   1.122
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.605
Skew:                          -0.907   Prob(JB):                     0.000150
Kurtosis:                       5.271   Cond. No.                     1.54e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.59e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [103]:
x_opt_train, x_opt_test, y_opt_train, y_opt_test = train_test_split(x_opt, y, test_size=0.2, random_state=0)

In [104]:
regressor = LinearRegression()
regressor.fit(x_opt_train, y_opt_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [105]:
y_opt_pred = regressor.predict(x_opt_test)

In [115]:
pd.DataFrame(y_opt_pred)

               0
0  104968.882398
1  133957.336222
2  135497.034913
3   72485.310557
4  179362.047197
5  109820.276771
6   65657.674769
7  100480.719947
8  111730.616593
9  169713.519068

In [116]:
pd.DataFrame(y_pred)

               0
0  103015.201598
1  132582.277608
2  132447.738452
3   71976.098513
4  178537.482211
5  116161.242302
6   67851.692097
7   98791.733747
8  113969.435330
9  167921.065695

In [117]:
pd.DataFrame(y_opt_test)

           0
0  103282.38
1  144259.40
2  146121.95
3   77798.83
4  191050.39
5  105008.31
6   81229.06
7   97483.56
8  110352.25
9  166187.94